### ISSUE TITLE
Support different themes

### ISSUE THREAD

**Issue by onedr0p** [stacc-as/custom-error-pages#1]
Hi 👋 @181192 

[tarampampam/error-pages](https://github.com/tarampampam/error-pages) is a pretty cool collection of custom themes, it would pretty neat to integrate those over here. You could probably use args or envars to switch between themes and even include your custom one as well!

**Comment by 181192** [comment]
Hi @onedr0p :relaxed: 

Agreed, could be nice. 
Now I'm just using a flag to point to a directory including templates ` --error-files-path` (that you can replace with out own).
It will however not work "as is" to point to files not being  go templates.
The idea was that you wanted a template to provide details/request information on the error page. But after using it in production it's preferred to hide that type of information from the end-user and instead extract from monitoring/tracing tools. 

One thing to mention, since this is a image that will most likely be added to the ingress-nginx helm chart config for default backend the configuration must be kept at a minimum to be simple to add for end-users. The ingress-nginx default chart do expose volume mounts etc for the default-backend. So providing extra files from a configmap or volume is possible for further customization.

**Comment by onedr0p** [comment]
> The idea was that you wanted a template to provide details/request information on the error page. But after using it in production it's preferred to hide that type of information from the end-user and instead extract from monitoring/tracing tools.

That's more config that can be changed via envars (which you have) and disabled by default.

> One thing to mention, since this is a image that will most likely be added to the ingress-nginx helm chart config for default backend the configuration must be kept at a minimum to be simple to add for end-users.

You're aiming to get this to replace the current default backend in the upstream helm chart? That's pretty neat but it shouldn't matter, we can make more customizable out of the box.

Anyways I'm willing to work on this and open a PR if you change your mind.

Thanks!

**Comment by onedr0p** [comment]
We could incorporate the themes to the errors file path config option instead of creating a theme config option. Does that work?
